### ISSUE TITLE
Issue with PAPI

### ISSUE THREAD

**Issue by Crsuh2er0** [MiaoCraft/HJYHunt#1]
[18:06:03 INFO]: [HJYHunt] 检测到PlaceHolderAPI插件，变量功能已启用！
[18:06:03 WARN]: [HJYHunt] Loaded class me.clip.placeholderapi.PlaceholderAPIPlugin from PlaceholderAPI v2.10.6 which is not a depend, softdepend or loadbefore of this plugin.
[18:06:03 ERROR]: Error occurred while enabling HJYHunt v3.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'me.clip.placeholderapi.expansion.manager.LocalExpansionManager me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()'
        at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:139) ~[?:?]
        at net.mcxk.hjyhunt.HJYHunt.onEnable(HJYHunt.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-120]
        at java.lang.Thread.run(Thread.java:832) [?:?]

### 开发者笔记
难度：普通
需要的时间：~6h

**Comment by Crsuh2er0** [comment]
[19:23:59] [Server thread/INFO]: [HJYHunt] Enabling HJYHunt v3.2
[19:23:59] [Server thread/INFO]: [HJYHunt] 检测到PlaceHolderAPI插件，变量功能已启用！
[19:23:59] [Server thread/ERROR]: Error occurred while enabling HJYHunt v3.2 (Is it up to date?)
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:139) ~[?:?]
        at net.mcxk.hjyhunt.HJYHunt.onEnable(HJYHunt.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:855) [?:1.8.0_322]

**Comment by Crsuh2er0** [comment]
暂时性的解决办法：
删除PAPI

**Comment by Crsuh2er0** [comment]
将删除PAPI支持
