### ISSUE TITLE
逃亡者在被非玩家击杀后仍可重生

### ISSUE THREAD

**Issue by Crsuh2er0** [MiaoCraft/HJYHunt#2]
[18:39:05 ERROR]: Could not pass event PlayerDeathEvent to HJYHunt v3.2
java.lang.NullPointerException: null
        at net.mcxk.hjyhunt.listener.GameWinnerListener.playerDeath(GameWinnerListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-120]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-120]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:820) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityPlayer.die(EntityPlayer.java:664) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:833) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityArrow.a(EntityArrow.java:333) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:125) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityArrow.tick(EntityArrow.java:176) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:831) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.World.a(World.java:932) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:525) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-120]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-120]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by Crsuh2er0** [comment]
将在v3.2中修复

**Comment by Crsuh2er0** [comment]
逃亡者被击杀后无法正常显示击杀者猎人
